### ISSUE TITLE
Mehrsprachigkeit & Safari

### ISSUE THREAD

**Issue by uschoenefeld** [TimoKoessler/QCaptcha#1]
Hi Timo,

wir möchten gerne Dein Plugin auf unsere Seite einsetzen und haben ein kleineres Problem.

1. Wir benutzen für die Mehrsprachigkeit "WPML & CF7" und würden gerne die Ausgabe auf Englisch (im Frontend) anbieten - wie ist das möglich?

Vielen Dank für Dein Feedback und Unterstützung.

Gruß Ulf

**Comment by uschoenefeld** [comment]
...das 2. Problem hat sich erledigt...:-)

**Comment by timokoessler** [comment]
Hallo,
die Sprache des Captchas richtet sich nach der im Browser des Webseiten-Besuchers eingerichteten Sprache. Wenn also jemand euer Kontaktformular aufruft und nicht Deutsch oder Niederländisch als bevorzugte Sprache verwendet, wird ihm das Captcha in Englisch angezeigt. Wenn ihr jedoch eine bestimmte Sprache manuell festlegen wollt, füge ich diese Funktion gerne zum WP-Plugin hinzu.
Gruß Timo

**Comment by uschoenefeld** [comment]
Hi Timo, 

das wäre super, wenn Du einen Parameter "Sprache" dem Shortcode hinzufügen könntest. Beispiel: [QCaptcha_cf7 lang="de"] - Ländercode als Parameter.  Oder gerne eine andere Lösung ;-)
Vielen Dank schon im Voraus. 

Gruß Ulf

**Comment by timokoessler** [comment]
Hallo,
ich habe gerade ein Update für das [WP-Plugin](https://wordpress.org/plugins/qcaptcha/) veröffentlicht (Version 1.0.1).
Es ist nun möglich die Sprache als Parameter zu übergeben. Zum Beispiel: `[qcaptcha_cf7 lang="en"]`.
Vorerst ist dies nur in Contact Form 7 Formularen möglich.
Viele Grüße,
Timo

**Comment by uschoenefeld** [comment]
Hi Timo,

super - das klappt :-) Vielen Dank für Deine schnelle Unterstützung und das Update. Hab es auf der Seite eingebaut und den Fehler-String (leeres "captcha") übersetzt mit WPML. Sieht jetzt klasse aus. Ein schönes Wochenende.

Viele Grüße Ulf
